services:
  - type: web
    name: vyoman-cross
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

